# Project Configuration
config:
  project_name: "curl"
  program_language: "c++"
  fuzz_projects_dir: "/home/cc/CKGFuzzer-1/fuzzing_llm_engine/external_database/curl/"
  work_dir: "/home/cc/CKGFuzzer-1/"
  shared_dir: "/home/cc/CKGFuzzer-1/docker_shared/"
  report_target_dir: "/linux/src/curl"
  time_budget: "1h"

  headers:
    - <curl/curl.h>
    - <stdlib.h>
    - <string.h>
    - <stdint.h>
    - <sstream>


llm_embedding:


# DeepSeek Analyzer Configuration
llm_analyzer:
  api_key: "sk-8abebb670dde4b098bcfe841b9f21e6f"
  #mdel: "qwen3-coder-flash"
  model: "qwen3-coder-plus"
  #proxy: "http://<ip>:<port>"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  temperature: 1.0
  context_window: 1000000


# DeepSeek Coder Configuration
llm_coder:
  api_key: "sk-8abebb670dde4b098bcfe841b9f21e6f"
  #model: "qwen3-coder-flash"
  model: "qwen3-coder-plus"
  #proxy: "http://<ip>:<port>"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  temperature: 0.7
  context_window: 1000000

